"""empty message

Revision ID: 3f5cdeb9b99e
Revises: d7dcdcb9a331
Create Date: 2018-11-30 15:33:04.589297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5cdeb9b99e'
down_revision = 'd7dcdcb9a331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=150), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('rights', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adminer_role_table',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['administrator.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'admin_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adminer_role_table')
    op.drop_table('role')
    # ### end Alembic commands ###
